//
// Created by wz on 24-2-2.
//

#ifndef AUTODDS_LIBS_MOVE_DETAIL_STD_NS_END_HPP_
#define AUTODDS_LIBS_MOVE_DETAIL_STD_NS_END_HPP_

#ifdef AUTODDS_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH
#pragma GCC diagnostic pop
#undef AUTODDS_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH
#endif   //AUTODDS_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH

#endif //AUTODDS_LIBS_MOVE_DETAIL_STD_NS_END_HPP_