//
// Created by wz on 24-3-1.
//

#ifndef AUTODDS_LIBS_CONTAINER_DETAIL_CONFIG_END_HPP_
#define AUTODDS_LIBS_CONTAINER_DETAIL_CONFIG_END_HPP_

#if defined(AUTODDS_GCC) && (AUTODDS_GCC >= 40600)
#pragma GCC diagnostic pop
#endif

#endif //AUTODDS_LIBS_CONTAINER_DETAIL_CONFIG_END_HPP_