//
// Created by wz on 24-3-12.
//

#ifndef AUTODDS_LIBS_INTERPROCESS_MEM_ALGO_DETAIL_MEM_ALGO_COMMON_HPP_
#define AUTODDS_LIBS_INTERPROCESS_MEM_ALGO_DETAIL_MEM_ALGO_COMMON_HPP_

#ifndef  AUTODDS_CONFIG_HPP
#  include "libs/config/config.hpp"
#endif
#

#if defined (AUTODDS_HAS_PRAGMA_ONCE)
#  pragma once
#endif

#endif //AUTODDS_LIBS_INTERPROCESS_MEM_ALGO_DETAIL_MEM_ALGO_COMMON_HPP_