//
// Created by wz on 24-2-1.
//

#ifndef AUTODDS_LIBS_CONFIG_DETAIL_CXX_COMPOSITE_HPP_
#define AUTODDS_LIBS_CONFIG_DETAIL_CXX_COMPOSITE_HPP_

#if defined(AUTODDS_NO_ADL_BARRIER)\
   || defined(AUTODDS_NO_ARGUMENT_DEPENDENT_LOOKUP)\
   || defined(AUTODDS_NO_ARRAY_TYPE_SPECIALIZATIONS)\
   || defined(AUTODDS_NO_COMPLETE_VALUE_INITIALIZATION)\
   || defined(AUTODDS_NO_CTYPE_FUNCTIONS)\
   || defined(AUTODDS_NO_CV_SPECIALIZATIONS)\
   || defined(AUTODDS_NO_CV_VOID_SPECIALIZATIONS)\
   || defined(AUTODDS_NO_CWCHAR)\
   || defined(AUTODDS_NO_CWCTYPE)\
   || defined(AUTODDS_NO_DEPENDENT_NESTED_DERIVATIONS)\
   || defined(AUTODDS_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS)\
   || defined(AUTODDS_NO_EXCEPTIONS)\
   || defined(AUTODDS_NO_EXCEPTION_STD_NAMESPACE)\
   || defined(AUTODDS_NO_EXPLICIT_FUNCTION_TEMPLATE_ARGUMENTS)\
   || defined(AUTODDS_NO_FENV_H)\
   || defined(AUTODDS_NO_FUNCTION_TEMPLATE_ORDERING)\
   || defined(AUTODDS_NO_FUNCTION_TYPE_SPECIALIZATIONS)\
   || defined(AUTODDS_NO_INCLASS_MEMBER_INITIALIZATION)\
   || defined(AUTODDS_NO_INTEGRAL_INT64_T)\
   || defined(AUTODDS_NO_INTRINSIC_WCHAR_T)\
   || defined(AUTODDS_NO_IOSFWD)\
   || defined(AUTODDS_NO_IOSTREAM)\
   || defined(AUTODDS_NO_IS_ABSTRACT)\
   || defined(AUTODDS_NO_LIMITS)\
   || defined(AUTODDS_NO_LIMITS_COMPILE_TIME_CONSTANTS)\
   || defined(AUTODDS_NO_LONG_LONG)\
   || defined(AUTODDS_NO_LONG_LONG_NUMERIC_LIMITS)\
   || defined(AUTODDS_NO_MEMBER_FUNCTION_SPECIALIZATIONS)\
   || defined(AUTODDS_NO_MEMBER_TEMPLATES)\
   || defined(AUTODDS_NO_MEMBER_TEMPLATE_FRIENDS)\
   || defined(AUTODDS_NO_MEMBER_TEMPLATE_KEYWORD)\
   || defined(AUTODDS_NO_NESTED_FRIENDSHIP)\
   || defined(AUTODDS_NO_OPERATORS_IN_NAMESPACE)\
   || defined(AUTODDS_NO_PARTIAL_SPECIALIZATION_IMPLICIT_DEFAULT_ARGS)\
   || defined(AUTODDS_NO_POINTER_TO_MEMBER_CONST)\
   || defined(AUTODDS_NO_POINTER_TO_MEMBER_TEMPLATE_PARAMETERS)\
   || defined(AUTODDS_NO_PRIVATE_IN_AGGREGATE)\
   || defined(AUTODDS_NO_RESTRICT_REFERENCES)\
   || defined(AUTODDS_NO_RTTI)\
   || defined(AUTODDS_NO_SFINAE)\
   || defined(AUTODDS_NO_SFINAE_EXPR)\
   || defined(AUTODDS_NO_STDC_NAMESPACE)\
   || defined(AUTODDS_NO_STD_ALLOCATOR)\
   || defined(AUTODDS_NO_STD_DISTANCE)\
   || defined(AUTODDS_NO_STD_ITERATOR)\
   || defined(AUTODDS_NO_STD_ITERATOR_TRAITS)\
   || defined(AUTODDS_NO_STD_LOCALE)\
   || defined(AUTODDS_NO_STD_MESSAGES)\
   || defined(AUTODDS_NO_STD_MIN_MAX)\
   || defined(AUTODDS_NO_STD_OUTPUT_ITERATOR_ASSIGN)\
   || defined(AUTODDS_NO_STD_TYPEINFO)\
   || defined(AUTODDS_NO_STD_USE_FACET)\
   || defined(AUTODDS_NO_STD_WSTREAMBUF)\
   || defined(AUTODDS_NO_STD_WSTRING)\
   || defined(AUTODDS_NO_STRINGSTREAM)\
   || defined(AUTODDS_NO_TEMPLATED_IOSTREAMS)\
   || defined(AUTODDS_NO_TEMPLATED_ITERATOR_CONSTRUCTORS)\
   || defined(AUTODDS_NO_TEMPLATE_PARTIAL_SPECIALIZATION)\
   || defined(AUTODDS_NO_TEMPLATE_TEMPLATES)\
   || defined(AUTODDS_NO_TWO_PHASE_NAME_LOOKUP)\
   || defined(AUTODDS_NO_TYPEID)\
   || defined(AUTODDS_NO_TYPENAME_WITH_CTOR)\
   || defined(AUTODDS_NO_UNREACHABLE_RETURN_DETECTION)\
   || defined(AUTODDS_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE)\
   || defined(AUTODDS_NO_USING_TEMPLATE)\
   || defined(AUTODDS_NO_VOID_RETURNS)
#    define AUTODDS_NO_CXX03
#endif

#if defined(AUTODDS_NO_CXX03)\
   || defined(AUTODDS_NO_CXX11_ADDRESSOF)\
   || defined(AUTODDS_NO_CXX11_ALIGNAS)\
   || defined(AUTODDS_NO_CXX11_ALIGNOF)\
   || defined(AUTODDS_NO_CXX11_ALLOCATOR)\
   || defined(AUTODDS_NO_CXX11_AUTO_DECLARATIONS)\
   || defined(AUTODDS_NO_CXX11_AUTO_MULTIDECLARATIONS)\
   || defined(AUTODDS_NO_CXX11_CHAR16_T)\
   || defined(AUTODDS_NO_CXX11_CHAR32_T)\
   || defined(AUTODDS_NO_CXX11_CONSTEXPR)\
   || defined(AUTODDS_NO_CXX11_DECLTYPE)\
   || defined(AUTODDS_NO_CXX11_DECLTYPE_N3276)\
   || defined(AUTODDS_NO_CXX11_DEFAULTED_FUNCTIONS)\
   || defined(AUTODDS_NO_CXX11_DEFAULTED_MOVES)\
   || defined(AUTODDS_NO_CXX11_DELETED_FUNCTIONS)\
   || defined(AUTODDS_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS)\
   || defined(AUTODDS_NO_CXX11_EXTERN_TEMPLATE)\
   || defined(AUTODDS_NO_CXX11_FINAL)\
   || defined(AUTODDS_NO_CXX11_FIXED_LENGTH_VARIADIC_TEMPLATE_EXPANSION_PACKS)\
   || defined(AUTODDS_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS)\
   || defined(AUTODDS_NO_CXX11_HDR_ARRAY)\
   || defined(AUTODDS_NO_CXX11_HDR_ATOMIC)\
   || defined(AUTODDS_NO_CXX11_HDR_CHRONO)\
   || defined(AUTODDS_NO_CXX11_HDR_CONDITION_VARIABLE)\
   || defined(AUTODDS_NO_CXX11_HDR_EXCEPTION)\
   || defined(AUTODDS_NO_CXX11_HDR_FORWARD_LIST)\
   || defined(AUTODDS_NO_CXX11_HDR_FUNCTIONAL)\
   || defined(AUTODDS_NO_CXX11_HDR_FUTURE)\
   || defined(AUTODDS_NO_CXX11_HDR_INITIALIZER_LIST)\
   || defined(AUTODDS_NO_CXX11_HDR_MUTEX)\
   || defined(AUTODDS_NO_CXX11_HDR_RANDOM)\
   || defined(AUTODDS_NO_CXX11_HDR_RATIO)\
   || defined(AUTODDS_NO_CXX11_HDR_REGEX)\
   || defined(AUTODDS_NO_CXX11_HDR_SYSTEM_ERROR)\
   || defined(AUTODDS_NO_CXX11_HDR_THREAD)\
   || defined(AUTODDS_NO_CXX11_HDR_TUPLE)\
   || defined(AUTODDS_NO_CXX11_HDR_TYPEINDEX)\
   || defined(AUTODDS_NO_CXX11_HDR_TYPE_TRAITS)\
   || defined(AUTODDS_NO_CXX11_HDR_UNORDERED_MAP)\
   || defined(AUTODDS_NO_CXX11_HDR_UNORDERED_SET)\
   || defined(AUTODDS_NO_CXX11_INLINE_NAMESPACES)\
   || defined(AUTODDS_NO_CXX11_LAMBDAS)\
   || defined(AUTODDS_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS)\
   || defined(AUTODDS_NO_CXX11_NOEXCEPT)\
   || defined(AUTODDS_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS)\
   || defined(AUTODDS_NO_CXX11_NULLPTR)\
   || defined(AUTODDS_NO_CXX11_NUMERIC_LIMITS)\
   || defined(AUTODDS_NO_CXX11_OVERRIDE)\
   || defined(AUTODDS_NO_CXX11_POINTER_TRAITS)\
   || defined(AUTODDS_NO_CXX11_RANGE_BASED_FOR)\
   || defined(AUTODDS_NO_CXX11_RAW_LITERALS)\
   || defined(AUTODDS_NO_CXX11_REF_QUALIFIERS)\
   || defined(AUTODDS_NO_CXX11_RVALUE_REFERENCES)\
   || defined(AUTODDS_NO_CXX11_SCOPED_ENUMS)\
   || defined(AUTODDS_NO_CXX11_SFINAE_EXPR)\
   || defined(AUTODDS_NO_CXX11_SMART_PTR)\
   || defined(AUTODDS_NO_CXX11_STATIC_ASSERT)\
   || defined(AUTODDS_NO_CXX11_STD_ALIGN)\
   || defined(AUTODDS_NO_CXX11_TEMPLATE_ALIASES)\
   || defined(AUTODDS_NO_CXX11_THREAD_LOCAL)\
   || defined(AUTODDS_NO_CXX11_TRAILING_RESULT_TYPES)\
   || defined(AUTODDS_NO_CXX11_UNICODE_LITERALS)\
   || defined(AUTODDS_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX)\
   || defined(AUTODDS_NO_CXX11_UNRESTRICTED_UNION)\
   || defined(AUTODDS_NO_CXX11_USER_DEFINED_LITERALS)\
   || defined(AUTODDS_NO_CXX11_VARIADIC_MACROS)\
   || defined(AUTODDS_NO_CXX11_VARIADIC_TEMPLATES)
#    define AUTODDS_NO_CXX11
#endif

#if defined(AUTODDS_NO_CXX11)\
   || defined(AUTODDS_NO_CXX14_AGGREGATE_NSDMI)\
   || defined(AUTODDS_NO_CXX14_BINARY_LITERALS)\
   || defined(AUTODDS_NO_CXX14_CONSTEXPR)\
   || defined(AUTODDS_NO_CXX14_DECLTYPE_AUTO)\
   || defined(AUTODDS_NO_CXX14_DIGIT_SEPARATORS)\
   || defined(AUTODDS_NO_CXX14_GENERIC_LAMBDAS)\
   || defined(AUTODDS_NO_CXX14_HDR_SHARED_MUTEX)\
   || defined(AUTODDS_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES)\
   || defined(AUTODDS_NO_CXX14_RETURN_TYPE_DEDUCTION)\
   || defined(AUTODDS_NO_CXX14_STD_EXCHANGE)\
   || defined(AUTODDS_NO_CXX14_VARIABLE_TEMPLATES)
#    define AUTODDS_NO_CXX14
#endif

#if defined(AUTODDS_NO_CXX14)\
   || defined(AUTODDS_NO_CXX17_DEDUCTION_GUIDES)\
   || defined(AUTODDS_NO_CXX17_FOLD_EXPRESSIONS)\
   || defined(AUTODDS_NO_CXX17_HDR_ANY)\
   || defined(AUTODDS_NO_CXX17_HDR_CHARCONV)\
   || defined(AUTODDS_NO_CXX17_HDR_EXECUTION)\
   || defined(AUTODDS_NO_CXX17_HDR_FILESYSTEM)\
   || defined(AUTODDS_NO_CXX17_HDR_MEMORY_RESOURCE)\
   || defined(AUTODDS_NO_CXX17_HDR_OPTIONAL)\
   || defined(AUTODDS_NO_CXX17_HDR_STRING_VIEW)\
   || defined(AUTODDS_NO_CXX17_HDR_VARIANT)\
   || defined(AUTODDS_NO_CXX17_IF_CONSTEXPR)\
   || defined(AUTODDS_NO_CXX17_INLINE_VARIABLES)\
   || defined(AUTODDS_NO_CXX17_ITERATOR_TRAITS)\
   || defined(AUTODDS_NO_CXX17_STD_APPLY)\
   || defined(AUTODDS_NO_CXX17_STD_INVOKE)\
   || defined(AUTODDS_NO_CXX17_STRUCTURED_BINDINGS)
#    define AUTODDS_NO_CXX17
#endif

#if defined(AUTODDS_NO_CXX17)\
   || defined(AUTODDS_NO_CXX20_HDR_BARRIER)\
   || defined(AUTODDS_NO_CXX20_HDR_BIT)\
   || defined(AUTODDS_NO_CXX20_HDR_COMPARE)\
   || defined(AUTODDS_NO_CXX20_HDR_CONCEPTS)\
   || defined(AUTODDS_NO_CXX20_HDR_COROUTINE)\
   || defined(AUTODDS_NO_CXX20_HDR_FORMAT)\
   || defined(AUTODDS_NO_CXX20_HDR_LATCH)\
   || defined(AUTODDS_NO_CXX20_HDR_NUMBERS)\
   || defined(AUTODDS_NO_CXX20_HDR_RANGES)\
   || defined(AUTODDS_NO_CXX20_HDR_SEMAPHORE)\
   || defined(AUTODDS_NO_CXX20_HDR_SOURCE_LOCATION)\
   || defined(AUTODDS_NO_CXX20_HDR_SPAN)\
   || defined(AUTODDS_NO_CXX20_HDR_STOP_TOKEN)\
   || defined(AUTODDS_NO_CXX20_HDR_SYNCSTREAM)\
   || defined(AUTODDS_NO_CXX20_HDR_VERSION)
#    define AUTODDS_NO_CXX20
#endif

#if defined(AUTODDS_NO_CXX20)\
   || defined(AUTODDS_NO_CXX23_HDR_EXPECTED)\
   || defined(AUTODDS_NO_CXX23_HDR_FLAT_MAP)\
   || defined(AUTODDS_NO_CXX23_HDR_FLAT_SET)\
   || defined(AUTODDS_NO_CXX23_HDR_GENERATOR)\
   || defined(AUTODDS_NO_CXX23_HDR_MDSPAN)\
   || defined(AUTODDS_NO_CXX23_HDR_PRINT)\
   || defined(AUTODDS_NO_CXX23_HDR_SPANSTREAM)\
   || defined(AUTODDS_NO_CXX23_HDR_STACKTRACE)\
   || defined(AUTODDS_NO_CXX23_HDR_STDFLOAT)
#    define AUTODDS_NO_CXX23
#endif


#endif //AUTODDS_LIBS_CONFIG_DETAIL_CXX_COMPOSITE_HPP_