//
// Created by wz on 24-2-1.
//

#ifndef AUTODDS_LIBS_CONFIG_HELPER_MACROS_HPP_
#define AUTODDS_LIBS_CONFIG_HELPER_MACROS_HPP_

// Converts the parameter X to a string after macro replacement
#define AUTODDS_STRINGIZE(X) AUTODDS_DO_STRINGIZE(X)
#define AUTODDS_DO_STRINGIZE(X) #X

#define AUTODDS_JOIN(X, Y) AUTODDS_DO_JOIN(X, Y)
#define AUTODDS_DO_JOIN(X, Y) AUTODDS_DO_JOIN2(X,Y)
#define AUTODDS_DO_JOIN2(X, Y) X##Y

#endif //AUTODDS_LIBS_CONFIG_HELPER_MACROS_HPP_