//
// Created by wz on 24-2-23.
//

#ifndef AUTODDS_LIBS_INTERPROCESS_DETAIL_MANAGED_MEMORY_IMPL_HPP_
#define AUTODDS_LIBS_INTERPROCESS_DETAIL_MANAGED_MEMORY_IMPL_HPP_

#ifndef  AUTODDS_CONFIG_HPP
#  include "libs/config/config.hpp"
#endif
#

#if defined (AUTODDS_HAS_PRAGMA_ONCE)
#  pragma once
#endif

#endif //AUTODDS_LIBS_INTERPROCESS_DETAIL_MANAGED_MEMORY_IMPL_HPP_