//
// Created by wz on 24-2-6.
//

#ifndef AUTODDS_LIBS_INTERPROCESS_DETAIL_TYPE_TRAITS_HPP_
#define AUTODDS_LIBS_INTERPROCESS_DETAIL_TYPE_TRAITS_HPP_

#endif //AUTODDS_LIBS_INTERPROCESS_DETAIL_TYPE_TRAITS_HPP_